# Linear Regression
Task:
 Решить задачу с применением линейной регрессии по датасет IRIS.
 Классы заменить на 0, 1 (вместо 3, сделать 2 класса)

In [60]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error

Загружаем датасет

In [5]:
from sklearn.datasets import load_iris
data = load_iris()

In [12]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Преобразуем в датафрейм

In [33]:
df = pd.DataFrame(data=np.c_[data['data']], columns=data['feature_names'])
df['target'] = data['target']
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

Делаем 2 класса вместо 3

In [34]:
df.target = df.target.replace({2: 1})
df.target.unique()

array([0, 1])

Делим датасет на две выборки: 2/3 для обучения и 1/3 для тестирования

In [67]:
X, y = df.iloc[::,:4], df.iloc[::, 4]
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size=0.67,
                                                    random_state=42)

Строим модель

In [72]:
reg = LinearRegression() # объявляем модель
reg.fit(X_train,y_train) # обучаем

LinearRegression()

In [73]:
reg.coef_

array([-0.07655625, -0.28061686,  0.22733715,  0.05746093])

In [74]:
reg.intercept_

1.0425484900525994

Выполним предсказание по построенной модели:

In [88]:
test_preds = reg.predict(X_test)
test_preds

array([ 0.92726591, -0.05645475,  1.42424805,  0.8786307 ,  0.90790244,
        0.03903754,  0.69315758,  0.93597774,  1.05975125,  0.79642475,
        0.92130028,  0.15724603, -0.05363939,  0.14426244, -0.05598843,
        0.79463061,  1.14805184,  0.86211328,  0.91816707,  1.16636341,
        0.15999181,  0.95108653,  0.09239375,  1.16061731,  0.94128971,
        1.00208439,  1.25006465,  1.0974414 ,  0.16873822,  0.18039787,
       -0.0810016 , -0.2645462 ,  0.74043815,  0.09621281,  0.11475754,
        1.10456352,  0.76382314,  0.01479491, -0.02068924, -0.1593213 ,
        1.10945199,  0.74406836,  0.81438539, -0.14673832, -0.05663971,
        0.84661706,  1.0201278 ,  1.03646026,  0.77615546,  1.01153178])

Среднеквадратическая ошибка

In [95]:
MSE = mean_squared_error(y_test,test_preds)
MSE

0.02403540888019987

Средняя абсолютная ошибка

In [96]:
MAE = mean_absolute_error(y_test,test_preds)
MAE

0.12880350695945053

Корень из среднеквадратичекой ошибки

In [97]:
RMSE = np.sqrt(MSE)
RMSE

0.15503357339686094

Коэффициент детерминации

In [98]:
reg.score(X, y)

0.9063478622197856